### ISSUE TITLE
8.1 php support

### ISSUE THREAD

**Issue by madmax01** [celane/pnp4nagios#2]
Hi Team,

https://www.php.net/supported-versions.php

8.0 is only a few month remaining supported

when i switch to 8.1 (because icinga supports it) > pnp fails with

```
Please check the documentation for information about the following error.
Automatic conversion of false to array is deprecated

file [line]:
templates.dist/default.php [65]:
```

**Comment by celane** [comment]
fixed with current release (0.6.27-2)
