### ISSUE TITLE
graph basket not working...

### ISSUE THREAD

**Issue by celane** [celane/pnp4nagios#3]
just needs some debug, worked recently.

**Comment by russellvt** [comment]
Please be more specific with what you think isn't working (ie. would be helpful for those of us trying to follow your fork).

**Comment by celane** [comment]
This is the "+" icon on graphs, that add them to the "basket" (on right side vertical bar) so you can make a custom set of graphs to plot.  

Found the bug; it's another php8.1+ complaint about trying to auto-create an array.  Fix will be put in place within an hour or two.
